# type: ignore
"""empty message.

Revision ID: 832581ac66f8
Revises: 9dabbbd6ed38
Create Date: 2025-10-02 23:20:35.545106

"""

import sqlalchemy as sa
from alembic import op
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = "832581ac66f8"
down_revision = "9dabbbd6ed38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "user_id",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None,
        "posts",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_column("posts", "user_id")
    # ### end Alembic commands ###
