"""empty message.

Revision ID: 0598075bd7bb
Revises: 832581ac66f8
Create Date: 2025-10-02 23:26:28.224587

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0598075bd7bb"
down_revision = "832581ac66f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("title", sa.String(length=255), nullable=False))
    op.drop_column("posts", "titile")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts",
        sa.Column(
            "titile",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("posts", "title")
    # ### end Alembic commands ###
